version: "3.8"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    container_name: Angular
    volumes:
      - ./frontend:/usr/app/
      - /usr/app/node_modules
    ports:
      - $ANGULAR_PORT
    links:
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: NestJS
    ports:
      # - $NEST_PORT
      - 9229:9229
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend:/app/
      - /app/node_modules
      - type: bind
        source: ./backend/upload
        target: /upload

  postgres:
    image: $POSTGRES_IMG
    container_name: PostgresSQL
    restart: always
    # ports:
      # - $PORT_DB:$PORT_DB
    env_file:
      - .env
    volumes:
      - $VOL_DB
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -h $HOST_DB -p $PORT_DB -U $POSTGRES_USER -d $POSTGRES_DB"]
        interval: 5s
        timeout: 5s
        retries: 5
volumes:
    postgres:
      name: db